version: "3.4"

networks:
  my_network:
    driver: bridge

services:
  php:
    build: docker-compose/php
    restart: always
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - my_network
  nginx:
    image: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    depends_on:
      - php
    networks:
      - my_network
